[wsl.files]
"wsl/.wslconfig" = "~/.wslconfig"

[git.files]
"git" = "~"

[elvish.files]
"elvish/rc" = "~/AppData/Roaming/elvish"
"elvish/starship.toml" = "~/.config/starship.toml"

[rime.files]
"Rime" = "~/AppData/Roaming/Rime"

[flow.files]
"FlowLauncher" = "~/AppData/Roaming/FlowLauncher"

[nvim.files]
"nvim" = "~/AppData/Local/nvim"
