[settings]
default_target_type = "symbolic"

[git.files]
"git" = "~"

[shell.files]
"shell/elvish" = "~/.config/elvish/"
"shell/carapace" = "~/.config/carapace/"
"shell/starship.toml" = "~/.config/starship.toml"

[helix.files]
"helix" = "~/.config/helix/"

[nvim.files]
"nvim" = "~/.config/nvim/"

[misc.files]
"misc/fastfetch.jsonc" = "~/.config/fastfetch/config.jsonc"

[secret.files]
"secret/ssh-config" = "~/.ssh/config"
"secret/ssh-config.local" = "~/.ssh/config.d/local"

[rime]
[nix]
[wsl]
[shim]
[flow]
