[settings]
default_target_type = "symbolic"

[git.files]
"git" = "~"

[elvish.files]
"elvish/rc" = "~/.config/elvish/"
"elvish/starship.toml" = "~/.config/starship.toml"

[rime.files]
"Rime" = "~/Library/Rime"

[nvim.files]
"nvim" = "~/.config/nvim"
