[settings]
default_target_type = "symbolic"

[git.files]
"git" = "~"

[shell.files]
"shell/elvish" = "~/.config/elvish/"
"shell/starship.toml" = "~/.config/starship.toml"

[nvim.files]
"nvim" = "~/.config/nvim"

[secret.files]
"secret/ssh-config" = "~/.ssh/config"

[rime]
[nix]
[wsl]
[shim]
[flow]
[misc]
