[default]
depends = ["git", "shell", "nvim", "rime", "wsl", "shim", "flow", "misc"]

[shell.files]
"shell/elvish" = "~/AppData/Roaming/elvish"

[nvim.files]
"nvim" = "~/AppData/Local/nvim"

[rime.files]
"rime" = "~/AppData/Roaming/Rime"
"rime/rime_ice.custom.windows.yaml" = "~/AppData/Roaming/Rime/rime_ice.custom.platform.yaml"

[wsl.files]
"wsl/.wslconfig" = "~/.wslconfig"

[shim.files]
"shim/shim.exe" = "~/.local/bin/shim.exe"
"shim/msys.exe" = "~/.local/bin/msys.exe"
"shim/msys.shim" = "~/.local/bin/msys.shim"

[flow.files]
"flow" = "~/AppData/Roaming/FlowLauncher"

[misc.files]
"misc/.pycodestyle" = "~/.pycodestyle"
