[default]
depends = ["git", "shell", "nvim", "rime", "wsl", "flow"]

[shell.files]
"shell/elvish" = "~/AppData/Roaming/elvish"

[nvim.files]
"nvim" = "~/AppData/Local/nvim"

[rime.files]
"rime" = "~/AppData/Roaming/Rime"

[wsl.files]
"wsl/.wslconfig" = "~/.wslconfig"

[flow.files]
"flow" = "~/AppData/Roaming/FlowLauncher"
